### ISSUE TITLE
what is the recommended specs?

### ISSUE THREAD

**Issue by tngh5004** [srcn-ivl/UPR-Net#4]
Hello, I am a ajou univ graduate student, interested in optical flow.
really thanks for revealing your code.

And i read your README for running the demo code, and followed the step intently.
but I received this error message,
"RuntimeError: Unable to find a valid cuDNN algorithm to run convolution"
(i was double check my conda enviorment cudatoolkit version is 10.2, and others too)
I googled it and they say it's my graphics card specs.

but i have RTX 4080 and 32gb ram pc, isn't it enough?

for reference, my enviorment is WSL 2 with ubuntu 22.04, cuda 12.2 with cudnn 8.92.
would i have to change the cuda version in WSL 2?

**Comment by starrysky-ashin** [comment]
Hi, thanks for your interest in our work. RTX 4080 and 32gb ram is enough to run our code. 

We developed and run our code only with Linux, and have not verfied the running environment with WSL2. Therefore, I cannot give exact answer to your question.

Could you try again with Linux based on our README?

**Comment by mhmtsarigul** [comment]
What about training. are 2 A5000 enough?
